### ISSUE TITLE
Drawing architecture diagrams with FMC (Fundamental Modeling Concepts)

### ISSUE THREAD

**Issue by drozzy** [drozzy/Information-Systems-Architecture-Meetup#4]
Talk about the FMC diagrams. Talk how it is better than UML. Show some examples and real-life use cases.

**Comment by koppor** [comment]
Seems to be solved: https://github.com/drozzy/Information-Systems-Architecture-Meetup/tree/master/2018-02-22-stop-using-uml-or-an-intro-to-fmc

**Comment by drozzy** [comment]
:-)
